[[redirects]]
  from = "/api/*"
  to = "http://webservice.recruit.co.jp/hotpepper/api/gourmet/v1/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
